//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int AccountID { get; set; }
        public int SubjectID { get; set; }
        public string Grade1 { get; set; }
        public System.DateTime AssignedAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
