//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSubject
    {
        public int ID { get; set; }
        public int Teacher { get; set; }
        public int Subject { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
